### ISSUE TITLE
unblock.html

### ISSUE THREAD

**Issue by SuperGamerGuard** [ouch13/g#1]
This html name combined with the website froze my screen completely.

**Comment by supsa-ak** [comment]
Hi, can I contribute on this repository. I am participating in Hacktoberfest. I can do any task assigned by you.

**Comment by SuperGamerGuard** [comment]
Whenever I pull up the website and add "unblock" to the end, it freezes my chromebook screen, preventing me from doing anything related to the chromebook until I close the system.

**Comment by supsa-ak** [comment]
Sorry I don't have a chromebook so I can't reproduce this issue. I can help with other bugs or contributions.

**Comment by SuperGamerGuard** [comment]
I just won't unblock.html, and I don't believe I've ran into any other bugs.
